Controllers/AdvicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SolomonsAdviceWebApp.Areas.Identity.Constants;
using SolomonsAdviceWebApp.Data;
using SolomonsAdviceWebApp.Models.Entities;

namespace SolomonsAdviceWebApp.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Manager)]
    public class AdvicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdvicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Advices
        public async Task<IActionResult> Index()
        {
            return View(await _context.Advices.ToListAsync());
        }

        // GET: Advices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advice = await _context.Advices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (advice == null)
            {
                return NotFound();
            }

            return View(advice);
        }

        // GET: Advices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Advices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Content,Chapter,Verses,Book")] Advice advice)
        {
            if (ModelState.IsValid)
            {
                _context.Add(advice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(advice);
        }

        // GET: Advices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advice = await _context.Advices.FindAsync(id);
            if (advice == null)
            {
                return NotFound();
            }
            return View(advice);
        }

        // POST: Advices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Content,Chapter,Verses,Book")] Advice advice)
        {
            if (id != advice.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(advice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdviceExists(advice.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(advice);
        }

        // GET: Advices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advice = await _context.Advices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (advice == null)
            {
                return NotFound();
            }

            return View(advice);
        }

        // POST: Advices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var advice = await _context.Advices.FindAsync(id);
            if (advice != null)
            {
                _context.Advices.Remove(advice);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdviceExists(int id)
        {
            return _context.Advices.Any(e => e.Id == id);
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Scripting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SolomonsAdviceWebApp.Data;
using SolomonsAdviceWebApp.Models;
using SolomonsAdviceWebApp.Models.Entities;
using SolomonsAdviceWebApp.Services;

namespace SolomonsAdviceWebApp.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {

        private readonly AdviceService _adviceService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ProfileController(AdviceService adviceService, UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _adviceService = adviceService;
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var favoriteAdvices = await _adviceService.GetFavoritesAsync(userId);
            return View(favoriteAdvices);
        }


        [HttpPost]
        public async Task<IActionResult> ToggleFavorite(int id)
        {
            string urlAnterior = Request.Headers["Referer"].ToString();
            // Medida temporária para contornar erro de direcionamento para action Home/AdviceOnCard
            if(urlAnterior == "https://localhost:7092/Home/AdviceOnCard")
            {
                urlAnterior = "https://localhost:7092/Profile";
            }
            var userId = _userManager.GetUserId(User);
            var existingFavorite = await _context.FavoriteAdvices
                .FirstOrDefaultAsync(fav => fav.AdviceId == id && fav.UserId == userId);

            if(existingFavorite != null)
            {
                _context.FavoriteAdvices.Remove(existingFavorite);
                await _context.SaveChangesAsync();
                return Redirect(urlAnterior);
            }
            else
            {
                await _context.FavoriteAdvices.AddAsync(new FavoriteAdvice
                {
                    AdviceId = id,
                    UserId = userId,
                    Id = Guid.NewGuid().ToString()
                });
                await _context.SaveChangesAsync();
                return Redirect(urlAnterior);
            }

        }
    }
}

Views/Shared/FavoriteIconPartial.cshtml
@model FavoriteIconViewModel
@using Microsoft.AspNetCore.Identity
@using Microsoft.EntityFrameworkCore
@inject SolomonsAdviceWebApp.Data.ApplicationDbContext _context
@inject Microsoft.AspNetCore.Identity.UserManager<IdentityUser> _userManager
@inject Microsoft.AspNetCore.Identity.SignInManager<IdentityUser> _signManager

<form asp-controller="Profile" asp-action="ToggleFavorite">
    <input type="hidden" name="id" value="@Model.AdviceId"/>
    <button type="submit" class="btn-icon">
        @if (Model.IsFavorite)
        {
            <img src="@Url.Content("~/Images/starFav.png")" alt="Star Favorite Icon">
        }
        else
        {
            <img src="@Url.Content("~/Images/starNoFav.png")" alt="Star No Favorite Icon">
        }
    </button>
</form>

Views/Shared/_Layout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Solomon’s Advice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SolomonsAdviceWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Solomon’s Advice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_LoginAdminPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SolomonsAdviceWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

Views/Shared/_LoginAdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using SolomonsAdviceWebApp.Areas.Identity.Constants
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    if (User.IsInRole(Roles.Admin))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin Area</a>
        </li>
    }

    if(User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Manager))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Advices" asp-action="Index">Manage Advices</a>
        </li>
    }
}