Areas/Admin/Controllers/AdminRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SolomonsAdviceWebApp.Areas.Admin.Models;
using SolomonsAdviceWebApp.Areas.Identity.Constants;
using System.ComponentModel.DataAnnotations;

namespace SolomonsAdviceWebApp.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class AdminRolesController : Controller
    {
       private readonly RoleManager<IdentityRole> _roleManager;
       private readonly UserManager<IdentityUser> _userManager;

        public AdminRolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public ActionResult Index() { return View(_roleManager.Roles); }

        public IActionResult Create() { return View(); }

        [HttpPost]
        public async Task<ActionResult> Create([Required] string name)
        {
            if(ModelState.IsValid)
            {
                IdentityResult identityResult = await _roleManager.CreateAsync(new IdentityRole(name));
                if(identityResult.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    Errors(identityResult);
                }
            }
            return View(name);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            IdentityRole identityRole = await _roleManager.FindByIdAsync(id);

            List<IdentityUser> members = new List<IdentityUser>();
            List<IdentityUser> nomMembers = new List<IdentityUser>();

            foreach(var user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, identityRole.Name) ? members : nomMembers;
                list.Add(user);
            }

            return View(new RoleEdit
            {
                Role = identityRole,
                Members = members,
                NonMembers = nomMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult identityResult;

            if(ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[]{} )
                {
                    IdentityUser identityUser = await _userManager.FindByIdAsync(userId);
                    if (identityUser != null)
                    {
                        identityResult = await _userManager.AddToRoleAsync(identityUser, model.RoleName);
                        if(!identityResult.Succeeded)
                        {
                            Errors(identityResult);
                        }
                    }
                }

                foreach(string userId in model.DeleteIds ?? new string[]{} )
                {
                    IdentityUser identityUser = await _userManager.FindByIdAsync(userId);
                    if(identityUser != null)
                    {
                        identityResult = await _userManager.RemoveFromRoleAsync(identityUser, model.RoleName);
                        if (!identityResult.Succeeded)
                        {
                            Errors(identityResult);
                        }
                    }
                }
            }
            if(ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return await Update(model.RoleId);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole identityRole = await _roleManager.FindByIdAsync(id);
            if (identityRole == null)
            {
                ModelState.AddModelError("", "Role not found");
            }
            return View(identityRole);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfrimed(string id)
        {
            IdentityRole identityRole = await _roleManager.FindByIdAsync(id);

            if (identityRole != null)
            {
                IdentityResult identityResult = await _roleManager.DeleteAsync(identityRole);
                if(identityResult.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    Errors(identityResult);
                }
            }
            else
            {
                ModelState.AddModelError("", "Role not found");
            }
            return View(nameof(Index), _roleManager.Roles);
        }

        private void Errors(IdentityResult result)
        {
            foreach(IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

Areas/Admin/Controllers/AdminUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SolomonsAdviceWebApp.Areas.Identity.Constants;

namespace SolomonsAdviceWebApp.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class AdminUsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        public AdminUsersController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var users = _userManager.Users;
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityUser identityUser = await _userManager.FindByIdAsync(id);
            if(identityUser == null)
            {
                ViewBag.ErrorMessage = "User not found!";
                return View("NotFound");
            }
            else
            {
                IdentityResult identityResult = await _userManager.DeleteAsync(identityUser);
                if(identityResult.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach(var error in  identityResult.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                return View(nameof(Index));
            }
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SolomonsAdviceWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Solomon’s Advice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">Manage Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Manage Roles</a>
                        </li>
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item me-2">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@User.Identity?.Name</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SolomonsAdviceWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>